apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: quarrelsome-tern-python 
  janus-idp.io/tekton: quarrelsome-tern-python
  backstage.io/kubernetes-id: quarrelsome-tern-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: quarrelsome-tern-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  